# Generated by Django 3.0 on 2020-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('facultyid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('batchincharge', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('mobileno', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='facultyattendance',
            fields=[
                ('date', models.DateField()),
                ('facultyid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('status_hour1', models.CharField(max_length=10)),
                ('status_hour2', models.CharField(max_length=10)),
                ('status_hour3', models.CharField(max_length=10)),
                ('status_hour4', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='facultyleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('assesmentno', models.IntegerField()),
                ('sub1', models.CharField(max_length=20)),
                ('sub2', models.CharField(max_length=20)),
                ('sub3', models.CharField(max_length=20)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sattendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('studentid', models.IntegerField()),
                ('status_hour1', models.CharField(max_length=10)),
                ('status_hour2', models.CharField(max_length=10)),
                ('status_hour3', models.CharField(max_length=10)),
                ('status_hour4', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobileno', models.IntegerField(blank=True, null=True)),
                ('admissiondate', models.DateField(blank=True, null=True)),
                ('guardian', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
